CREATE TABLE `carnum` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`online` INT(10) NULL DEFAULT '0',
	`offline` INT(10) NULL DEFAULT '0',
	`time` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
AUTO_INCREMENT=117;
